---
name: redsocks

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: redsocks
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: net-bosh-2}]
  jobs:
  - name: redsocks-pkg-install
    release: redsocks
  - name: redsocks
    release: redsocks
    properties:
     remote-proxy:
       ip: 192.168.116.130
       port: 3128

variables: []

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  version: 0.12.3
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
- name: redsocks
  version: latest  # TODO: update after first final release
