---
processes:
- name: redsocks
  executable: /usr/sbin/redsocks 
  args:
  - -c
  - /var/vcap/jobs/redsocks/config/redsocks.conf
  ephemeral_disk: true
  persistent_disk: false
  env:
    PORT: <%= p("port") %>
  limits:
    memory: 1G
    open_files: 1024

# examples/docs at:
# - https://github.com/cloudfoundry-incubator/bpm-release/blob/master/jobs/test-server/templates/bpm.yml.erb
# - https://github.com/cloudfoundry-incubator/bpm-release/tree/master/docs
